"""token usage table

Revision ID: 55ca5286fb5b
Revises: ca83ddef3136
Create Date: 2026-08-29 09:56:39.655283

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "55ca5286fb5b"
down_revision: str | Sequence[str] | None = "ca83ddef3136"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token_usage",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("ref_id", sa.UUID(), nullable=True),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_cny", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("missing_calls", sa.Integer(), server_default="0", nullable=False),
        sa.Column("by_node", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_token_usage_company_id"), "token_usage", ["company_id"], unique=False
    )
    op.create_index(
        "ix_token_usage_owner_created",
        "token_usage",
        ["owner_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_token_usage_owner_created", table_name="token_usage")
    op.drop_index(op.f("ix_token_usage_company_id"), table_name="token_usage")
    op.drop_table("token_usage")
    # ### end Alembic commands ###
